version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"      # API 端口
      - "9001:9001"      # Console 端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  argus-frontend:
    build: 
      context: ./argus-vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - argus-backend
    networks:
      - argus-network

  argus-backend:
    build: 
      context: ./argus-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - minio
    environment:
      - MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
      - MINIO_ENDPOINT=minio:9000
    networks:
      - argus-network

networks:
  argus-network:
    driver: bridge

volumes:
  minio_data:
  mongodb_data: 