USE snake_skin;

-- 修复users表结构
-- 1. 删除updated_at列
ALTER TABLE users DROP COLUMN updated_at;

-- 2. 调整列的顺序和类型
ALTER TABLE users 
  MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY,
  MODIFY COLUMN username VARCHAR(50) UNIQUE NOT NULL,
  MODIFY COLUMN email VARCHAR(100) UNIQUE NOT NULL,
  MODIFY COLUMN hashed_password VARCHAR(100) NOT NULL,
  MODIFY COLUMN is_active BOOLEAN DEFAULT TRUE,
  MODIFY COLUMN is_superuser BOOLEAN DEFAULT FALSE,
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN last_login DATETIME NULL,
  MODIFY COLUMN login_attempts INT DEFAULT 0,
  MODIFY COLUMN last_login_attempt DATETIME NULL; 