name: Argus CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'argus-backend/**'
      - 'argus-vue/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'argus-backend/**'
      - 'argus-vue/**'
      - '.github/workflows/**'

env:
  MONGODB_URL: mongodb://localhost:27017
  MINIO_ENDPOINT: localhost:9000
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  MINIO_BUCKET_NAME: argus-samples
  MINIO_SECURE: "false"
  STORAGE_TYPE: "minio"

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
          MINIO_BROWSER: "on"
          MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
        options: >-
          server /data --console-address ":9001"

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        working-directory: ./argus-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Initialize test environment
        working-directory: ./argus-backend
        run: |
          python scripts/init_test_env.py
          
      - name: Check MinIO health
        run: |
          for i in {1..30}; do
            if curl -s -f http://localhost:9000/minio/health/live > /dev/null; then
              echo "MinIO is healthy"
              exit 0
            fi
            echo "Waiting for MinIO to be ready..."
            sleep 2
          done
          echo "MinIO health check failed"
          exit 1
          
      - name: Run tests
        working-directory: ./argus-backend
        run: |
          pytest
          
      - name: Build backend
        working-directory: ./argus-backend
        run: |
          python setup.py sdist bdist_wheel
          
      - name: Upload backend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: ./argus-backend/dist

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        working-directory: ./argus-vue
        run: npm ci
        
      - name: Run linting
        working-directory: ./argus-vue
        run: npm run lint
        
      - name: Run tests
        working-directory: ./argus-vue
        run: npm run test:unit
        
      - name: Build frontend
        working-directory: ./argus-vue
        run: npm run build
        
      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./argus-vue/dist 